using Microsoft.CodeAnalysis;
using static Macaron.InterfaceDelegation.Tests.Helper;

namespace Macaron.InterfaceDelegation.Tests;

[TestFixture]
public sealed class ExposeGenerationTests
{
    [Test]
    public void GeneratesDelegation_When_OmitTypeOfExposeAttribute()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeter
            {
                string Greet(string name);
            }

            public class RealGreeter : IGreeter
            {
                public string Greet(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeter
            {
                [Expose]
                private readonly IGreeter _impl = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IGreeter
                    public string Greet(string name)
                        => _impl.Greet(name);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_When_ExposeAttributeAppliedToField()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeter
            {
                string Greet(string name);
            }

            public class RealGreeter : IGreeter
            {
                public string Greet(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeter
            {
                [Expose(typeof(IGreeter))]
                private readonly IGreeter _impl = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IGreeter
                    public string Greet(string name)
                        => _impl.Greet(name);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_When_ExposeAttributeAppliedToProperty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeter
            {
                string Greet(string name);
            }

            public class RealGreeter : IGreeter
            {
                public string Greet(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeter
            {
                [Expose(typeof(IGreeter))]
                private IGreeter Impl { get; } = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IGreeter
                    public string Greet(string name)
                        => Impl.Greet(name);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_ForMultipleInheritedInterfaces()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeterA
            {
                string GreetA(string name);
            }

            public interface IGreeterB : IGreeterA
            {
                string GreetB(string name);
            }

            public interface IGreeterC : IGreeterA, IGreeterB
            {
                string GreetC(string name);
            }

            public class RealGreeter : IGreeterC
            {
                public string GreetA(string name) => $"Hello, {name}!";

                public string GreetB(string name) => $"Hello, {name}!";

                public string GreetC(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeterC
            {
                [Expose(typeof(IGreeterC))]
                private IGreeterC Impl { get; } = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IGreeterC
                    public string GreetC(string name)
                        => Impl.GreetC(name);

                    public string GreetB(string name)
                        => Impl.GreetB(name);

                    public string GreetA(string name)
                        => Impl.GreetA(name);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_ForMultipleInterfaces_OnSingleMember()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeterA
            {
                string GreetA(string name);
            }

            public interface IGreeterB
            {
                string GreetB(string name);
            }

            public class RealGreeter : IGreeterA, IGreeterB
            {
                public string GreetA(string name) => $"Hello, {name}!";

                public string GreetB(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeterA, IGreeterB
            {
                [Expose(typeof(IGreeterA))]
                [Expose(typeof(IGreeterB))]
                private RealGreeter Impl { get; } = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IGreeterA
                    public string GreetA(string name)
                    {
                        return ((global::Macaron.InterfaceDelegation.Tests.IGreeterA)Impl).GreetA(name);
                    }
                    #endregion

                    #region global::Macaron.InterfaceDelegation.Tests.IGreeterB
                    public string GreetB(string name)
                    {
                        return ((global::Macaron.InterfaceDelegation.Tests.IGreeterB)Impl).GreetB(name);
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesExplicitDelegation_ForMultipleInterfaces_OnSingleMember()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            using System;

            public interface IGreeterA
            {
                string Greet(string name);

                float this[int index] { get; set; }

                int Value { get; }
            }

            public interface IGreeterB
            {
                void Greet();

                float this[int index] { get; }

                string Value { get; set; }
            }

            public class RealGreeter : IGreeterA, IGreeterB
            {
                string IGreeterA.Greet(string name) => $"Hello, {name}!";

                int IGreeterA.Value => 42;

                float IGreeterA.this[int index]
                {
                    get => 0.0f;
                    set => throw new NotImplementedException();
                }

                void IGreeterB.Greet() { }

                string IGreeterB.Value
                {
                    get => "Hello, world!";
                    set => throw new NotImplementedException();
                }

                float IGreeterB.this[int index]
                {
                    get => 3.14f;
                }
            }

            public partial class TestClass : IGreeterA, IGreeterB
            {
                [Expose(typeof(IGreeterA), ImplementationMode.Explicit)]
                [Expose(typeof(IGreeterB), ImplementationMode.Explicit)]
                private RealGreeter Impl { get; } = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IGreeterA
                    string global::Macaron.InterfaceDelegation.Tests.IGreeterA.Greet(string name)
                    {
                        return ((global::Macaron.InterfaceDelegation.Tests.IGreeterA)Impl).Greet(name);
                    }

                    float global::Macaron.InterfaceDelegation.Tests.IGreeterA.this[int index]
                    {
                        get => ((global::Macaron.InterfaceDelegation.Tests.IGreeterA)Impl)[index];
                        set => ((global::Macaron.InterfaceDelegation.Tests.IGreeterA)Impl)[index] = value;
                    }

                    int global::Macaron.InterfaceDelegation.Tests.IGreeterA.Value
                    {
                        get => ((global::Macaron.InterfaceDelegation.Tests.IGreeterA)Impl).Value;
                    }
                    #endregion

                    #region global::Macaron.InterfaceDelegation.Tests.IGreeterB
                    void global::Macaron.InterfaceDelegation.Tests.IGreeterB.Greet()
                    {
                        ((global::Macaron.InterfaceDelegation.Tests.IGreeterB)Impl).Greet();
                    }

                    float global::Macaron.InterfaceDelegation.Tests.IGreeterB.this[int index]
                    {
                        get => ((global::Macaron.InterfaceDelegation.Tests.IGreeterB)Impl)[index];
                    }

                    string global::Macaron.InterfaceDelegation.Tests.IGreeterB.Value
                    {
                        get => ((global::Macaron.InterfaceDelegation.Tests.IGreeterB)Impl).Value;
                        set => ((global::Macaron.InterfaceDelegation.Tests.IGreeterB)Impl).Value = value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_ForMultipleInterfaces_OnSeparateMembers()
    {
        AssertGeneratedCodes(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeterA
            {
                string GreetA(string name);
            }

            public interface IGreeterB
            {
                string GreetB(string name);
            }

            public class RealGreeter : IGreeterA, IGreeterB
            {
                public string GreetA(string name) => $"Hello, {name}!";

                public string GreetB(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeterA, IGreeterB
            {
                [Expose(typeof(IGreeterA))]
                private IGreeterA ImplA { get; } = new RealGreeter();

                [Expose(typeof(IGreeterB))]
                private IGreeterB ImplB { get; } = new RealGreeter();
            }
            """,
            expected:
            [
                """
                // <auto-generated />
                #nullable enable

                namespace Macaron.InterfaceDelegation.Tests
                {
                    partial class TestClass
                    {
                        #region global::Macaron.InterfaceDelegation.Tests.IGreeterA
                        public string GreetA(string name)
                            => ImplA.GreetA(name);
                        #endregion
                    }
                }

                """,
                """
                // <auto-generated />
                #nullable enable

                namespace Macaron.InterfaceDelegation.Tests
                {
                    partial class TestClass
                    {
                        #region global::Macaron.InterfaceDelegation.Tests.IGreeterB
                        public string GreetB(string name)
                            => ImplB.GreetB(name);
                        #endregion
                    }
                }

                """,
            ]
        );
    }

    [Test]
    public void GeneratesDelegation_ForBoundedGenericInterface()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo<T1, T2>
            {
                T1 Bar { get; }

                T2 Baz { get; }
            }

            public class FooImpl : IFoo<int, string>
            {
                public int Bar => 42;

                public string Baz => "Hello, world!";
            }

            public partial class BoundedGenericInterfaceDelegation : IFoo<int, string>
            {
                [Expose(typeof(IFoo<int, string>))]
                private readonly FooImpl _impl = new FooImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class BoundedGenericInterfaceDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IFoo<int, string>
                    public int Bar
                    {
                        get
                        {
                            return __Get(in _impl);

                            #region Local Functions
                            static int __Get<__TImpl>(in __TImpl __impl) where __TImpl : global::Macaron.InterfaceDelegation.Tests.IFoo<int, string> => __impl.Bar;
                            #endregion
                        }
                    }

                    public string Baz
                    {
                        get
                        {
                            return __Get(in _impl);

                            #region Local Functions
                            static string __Get<__TImpl>(in __TImpl __impl) where __TImpl : global::Macaron.InterfaceDelegation.Tests.IFoo<int, string> => __impl.Baz;
                            #endregion
                        }
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_ForPropertiesAndIndexer()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            using System.Collections.Generic;

            public interface IPropertyExample
            {
                int Id { get; set; }

                string Name { get; }

                string this[int index] { get; set; }
            }

            public class PropertyExampleImpl : IPropertyExample
            {
                private readonly Dictionary<int, string> _data = new();

                public int Id { get; set; }

                public string Name => "Example";

                public string this[int index]
                {
                    get => _data[index];
                    set => _data[index] = value;
                }
            }

            public partial class TestPropertyDelegation : IPropertyExample
            {
                [Expose(typeof(IPropertyExample))]
                private readonly IPropertyExample _impl = new PropertyExampleImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPropertyDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IPropertyExample
                    public int Id
                    {
                        get => _impl.Id;
                        set => _impl.Id = value;
                    }

                    public string Name
                    {
                        get => _impl.Name;
                    }

                    public string this[int index]
                    {
                        get => _impl[index];
                        set => _impl[index] = value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_ForOverloadedMethods()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface ICalculator
            {
                int Add(int a, int b);

                double Add(double a, double b);
            }

            public class CalculatorImpl : ICalculator
            {
                public int Add(int a, int b) => a + b;

                public double Add(double a, double b) => a + b;
            }

            public partial class TestMethodOverloads : ICalculator
            {
                [Expose(typeof(ICalculator))]
                private readonly ICalculator _impl = new CalculatorImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestMethodOverloads
                {
                    #region global::Macaron.InterfaceDelegation.Tests.ICalculator
                    public int Add(int a, int b)
                        => _impl.Add(a, b);

                    public double Add(double a, double b)
                        => _impl.Add(a, b);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_InStructType()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IStructInterface
            {
                void DoSomething();
            }

            public class StructImpl : IStructInterface
            {
                public void DoSomething() { }
            }

            public partial struct TestStructDelegation : IStructInterface
            {
                [Expose(typeof(IStructInterface))]
                private readonly IStructInterface _impl;

                public TestStructDelegation()
                {
                    _impl = new StructImpl();
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial struct TestStructDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IStructInterface
                    public void DoSomething()
                        => _impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_InRecordType()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IRecordInterface
            {
                void DoSomething();
            }

            public class RecordImpl : IRecordInterface
            {
                public void DoSomething() { }
            }

            public partial record TestRecordDelegation([Expose(typeof(IRecordInterface))] IRecordInterface Impl) : IRecordInterface
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial record TestRecordDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IRecordInterface
                    public void DoSomething()
                        => Impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_InRecordStructType()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IRecordInterface
            {
                void DoSomething();
            }

            public class RecordImpl : IRecordInterface
            {
                public void DoSomething() { }
            }

            public partial record struct TestRecordDelegation([Expose(typeof(IRecordInterface))] IRecordInterface Impl) : IRecordInterface
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial record struct TestRecordDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IRecordInterface
                    public void DoSomething()
                        => Impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_ForGenericMethod()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGenericExample
            {
                int GetAnswer<T>() where T : class;
            }

            public class GenericExampleImpl : IGenericExample
            {
                public int GetAnswer<T>() where T : class => 42;
            }

            public partial class TestGenericDelegation : IGenericExample
            {
                [Expose(typeof(IGenericExample))]
                private readonly IGenericExample _impl = new GenericExampleImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestGenericDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IGenericExample
                    public int GetAnswer<T>()
                        where T : class
                        => _impl.GetAnswer<T>();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void UnsupportedIndexerAttribute_DoesNotSuppressSupportedExposeTarget()
    {
        const string sourceCode =
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void Run();
            }

            public sealed class Foo : IFoo
            {
                public void Run() { }
            }

            public partial class Wrapper
            {
                private readonly IFoo _indexerValue = new Foo();

                [Expose(typeof(IFoo))]
                public IFoo this[int index] => _indexerValue;

                [Expose(typeof(IFoo))]
                private readonly IFoo _impl = new Foo();
            }
            """;

        var result = RunGenerator(sourceCode);

        AssertSuccessfulGeneration(result);
        Assert.Multiple(() =>
        {
            Assert.That(result.Diagnostics, Has.None.Matches<Diagnostic>(static diagnostic => diagnostic.Id == "MAID0003"));
            Assert.That(result.GeneratedSources, Has.Length.EqualTo(1));
            Assert.That(result.GeneratedSources[0].SourceText.ToString(), Does.Contain("=> _impl.Run();"));
        });
    }
}
