using static Macaron.InterfaceDelegation.Tests.Helper;

namespace Macaron.InterfaceDelegation.Tests;

[TestFixture]
public sealed class ExposeExistingMemberTests
{
    [Test]
    public void SkipsAlreadyImplementedImplicitMembers_When_UsingDefaultMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialDefaultImplicit : IFoo
            {
                [Expose(typeof(IFoo))]
                private readonly IFoo _impl = new FooImpl();

                public void MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialDefaultImplicit
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAlreadyImplementedExplicitMembers_When_UsingDefaultMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialDefaultExplicit : IFoo
            {
                [Expose(typeof(IFoo))]
                private readonly IFoo _impl = new FooImpl();

                void IFoo.MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialDefaultExplicit
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesFullDelegation_When_UsingImplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialImplicit : IFoo
            {
                [Expose(typeof(IFoo), ImplementationMode.Implicit)]
                private readonly IFoo _impl = new FooImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialImplicit
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodA()
                        => _impl.MethodA();

                    public void MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAlreadyImplementedImplicitMembers_When_UsingImplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialImplicit : IFoo
            {
                [Expose(typeof(IFoo), ImplementationMode.Implicit)]
                private readonly IFoo _impl = new FooImpl();

                public void MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialImplicit
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAlreadyImplementedExplicitMembers_When_UsingImplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialImplicit : IFoo
            {
                [Expose(typeof(IFoo), ImplementationMode.Implicit)]
                private readonly IFoo _impl = new FooImpl();

                void IFoo.MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialImplicit
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesExplicitDelegation_When_UsingExplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IService
            {
                void Execute();
            }

            public class ServiceImpl : IService
            {
                public void Execute() { }
            }

            public partial class TestExplicitMode : IService
            {
                [Expose(typeof(IService), ImplementationMode.Explicit)]
                private readonly IService _impl = new ServiceImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestExplicitMode
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IService
                    void global::Macaron.InterfaceDelegation.Tests.IService.Execute()
                        => _impl.Execute();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAlreadyImplementedExplicitMembers_When_UsingExplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialExplicit : IFoo
            {
                [Expose(typeof(IFoo), ImplementationMode.Explicit)]
                private readonly IFoo _impl = new FooImpl();

                void IFoo.MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialExplicit
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IFoo
                    void global::Macaron.InterfaceDelegation.Tests.IFoo.MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesExplicitDelegation_EvenIfImplicitExists()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialExplicit : IFoo
            {
                [Expose(typeof(IFoo), ImplementationMode.Explicit)]
                private readonly IFoo _impl = new FooImpl();

                public void MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialExplicit
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IFoo
                    void global::Macaron.InterfaceDelegation.Tests.IFoo.MethodA()
                        => _impl.MethodA();

                    void global::Macaron.InterfaceDelegation.Tests.IFoo.MethodB()
                        => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAbstractMembers_InSameClass_When_GeneratingDelegation()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IAbstractExample
            {
                int GetAnswer();

                void DoSomething();
            }

            public class AbstractExampleImpl : IAbstractExample
            {
                public int GetAnswer() => 42;

                public void DoSomething() { }
            }

            public abstract partial class TestAbstractDelegation : IAbstractExample
            {
                [Expose(typeof(IAbstractExample))]
                private readonly IAbstractExample _impl = new AbstractExampleImpl();

                public abstract int GetAnswer();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestAbstractDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IAbstractExample
                    public void DoSomething()
                        => _impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesOverride_ForAbstractMembers_InBaseClass()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IAbstractExample
            {
                int GetAnswer();

                int Value { get; }
            }

            public class AbstractExampleImpl : IAbstractExample
            {
                public int GetAnswer() => 42;

                public int Value { get => 42; }
            }

            public abstract class TestAbstractDelegationBase
            {
                public abstract int GetAnswer();

                public abstract int Value { get; }
            }

            public partial class TestAbstractDelegation : TestAbstractDelegationBase, IAbstractExample
            {
                [Expose(typeof(IAbstractExample))]
                private readonly IAbstractExample _impl = new AbstractExampleImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestAbstractDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IAbstractExample
                    public override int GetAnswer()
                        => _impl.GetAnswer();

                    public override int Value
                    {
                        get => _impl.Value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsOverriddenMembers_InCurrentClass_When_GeneratingDelegation()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IAbstractExample
            {
                int GetAnswer();

                void DoSomething();

                int Value { get; }
            }

            public class AbstractExampleImpl : IAbstractExample
            {
                public int GetAnswer() => 42;

                public void DoSomething() { }

                public int Value { get => 42; }
            }

            public abstract class TestAbstractDelegationBase
            {
                public abstract int GetAnswer();

                public abstract int Value { get; }
            }

            public partial class TestAbstractDelegation : TestAbstractDelegationBase
            {
                [Expose(typeof(IAbstractExample))]
                private readonly IAbstractExample _impl = new AbstractExampleImpl();

                public override int GetAnswer() => 42;

                public override int Value { get => 42; }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestAbstractDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.IAbstractExample
                    public void DoSomething()
                        => _impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }
}
