using static Macaron.InterfaceDelegation.Tests.Helper;

namespace Macaron.InterfaceDelegation.Tests;

[TestFixture]
public sealed class ExposeEventTests
{
    [Test]
    public void GeneratesDelegation_ForEvent()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            using System;

            public interface INotifier
            {
                event EventHandler? Changed;
            }

            public class NotifierImpl : INotifier
            {
                public event EventHandler? Changed;
            }

            public partial class TestEventDelegation : INotifier
            {
                [Expose(typeof(INotifier))]
                private readonly INotifier _impl = new NotifierImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestEventDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.INotifier
                    public event global::System.EventHandler? Changed
                    {
                        add => _impl.Changed += value;
                        remove => _impl.Changed -= value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesOverride_ForEvent_InBaseClass()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            using System;

            public interface INotifier
            {
                event EventHandler? Changed;
            }

            public class NotifierImpl : INotifier
            {
                public event EventHandler? Changed;
            }

            public abstract class TestEventDelegationBase
            {
                public abstract event EventHandler? Changed;
            }

            public partial class TestEventDelegation : TestEventDelegationBase, INotifier
            {
                [Expose(typeof(INotifier))]
                private readonly INotifier _impl = new NotifierImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestEventDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.INotifier
                    public override event global::System.EventHandler? Changed
                    {
                        add => _impl.Changed += value;
                        remove => _impl.Changed -= value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_ForEvent_When_ExposeAttributeAppliedToProperty()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            using System;

            public interface INotifier
            {
                event EventHandler? Changed;
            }

            public class NotifierImpl : INotifier
            {
                public event EventHandler? Changed;
            }

            public partial class TestEventDelegation : INotifier
            {
                [Expose(typeof(INotifier))]
                private INotifier Impl { get; } = new NotifierImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestEventDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.INotifier
                    public event global::System.EventHandler? Changed
                    {
                        add => Impl.Changed += value;
                        remove => Impl.Changed -= value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesExplicitDelegation_ForEvent_When_UsingExplicitMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            using System;

            public interface INotifier
            {
                event EventHandler? Changed;
            }

            public class NotifierImpl : INotifier
            {
                public event EventHandler? Changed;
            }

            public partial class TestExplicitEventDelegation : INotifier
            {
                [Expose(typeof(INotifier), ImplementationMode.Explicit)]
                private readonly INotifier _impl = new NotifierImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestExplicitEventDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.INotifier
                    event global::System.EventHandler? global::Macaron.InterfaceDelegation.Tests.INotifier.Changed
                    {
                        add => _impl.Changed += value;
                        remove => _impl.Changed -= value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsAlreadyImplementedEvent_When_UsingDefaultMode()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            using System;

            public interface INotifier
            {
                event EventHandler? Changed;

                void Notify();
            }

            public class NotifierImpl : INotifier
            {
                public event EventHandler? Changed;

                public void Notify() { }
            }

            public partial class TestPartialDefaultEvent : INotifier
            {
                [Expose(typeof(INotifier))]
                private readonly INotifier _impl = new NotifierImpl();

                public event EventHandler? Changed;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialDefaultEvent
                {
                    #region global::Macaron.InterfaceDelegation.Tests.INotifier
                    public void Notify()
                        => _impl.Notify();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void SkipsOverriddenEvent_InCurrentClass_When_GeneratingDelegation()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            using System;

            public interface INotifier
            {
                event EventHandler? Changed;

                void Notify();
            }

            public class NotifierImpl : INotifier
            {
                public event EventHandler? Changed;

                public void Notify() { }
            }

            public abstract class TestEventDelegationBase
            {
                public abstract event EventHandler? Changed;
            }

            public partial class TestEventDelegation : TestEventDelegationBase, INotifier
            {
                [Expose(typeof(INotifier))]
                private readonly INotifier _impl = new NotifierImpl();

                public override event EventHandler? Changed
                {
                    add { }
                    remove { }
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestEventDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.INotifier
                    public void Notify()
                        => _impl.Notify();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void GeneratesDelegation_ForExplicitlyImplementedEvent_OnConcreteType()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            using System;

            public interface INotifier
            {
                event EventHandler? Changed;
            }

            public class NotifierImpl : INotifier
            {
                event EventHandler? INotifier.Changed
                {
                    add { }
                    remove { }
                }
            }

            public partial class TestEventDelegation : INotifier
            {
                [Expose(typeof(INotifier))]
                private readonly NotifierImpl _impl = new NotifierImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestEventDelegation
                {
                    #region global::Macaron.InterfaceDelegation.Tests.INotifier
                    public event global::System.EventHandler? Changed
                    {
                        add
                        {
                            __Add(in _impl, value);

                            #region Local Functions
                            static void __Add<__TImpl>(in __TImpl __impl, global::System.EventHandler? value) where __TImpl : global::Macaron.InterfaceDelegation.Tests.INotifier => __impl.Changed += value;
                            #endregion
                        }
                        remove
                        {
                            __Remove(in _impl, value);

                            #region Local Functions
                            static void __Remove<__TImpl>(in __TImpl __impl, global::System.EventHandler? value) where __TImpl : global::Macaron.InterfaceDelegation.Tests.INotifier => __impl.Changed -= value;
                            #endregion
                        }
                    }
                    #endregion
                }
            }

            """
        );
    }
}
