using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Macaron.InterfaceDelegation.Tests;

[TestFixture]
public class InterfaceDelegationGeneratorTests
{
    private static void Assert(string sourceCode, string expected)
    {
        var references = AppDomain
            .CurrentDomain
            .GetAssemblies()
            .Where(assembly => !assembly.IsDynamic && !string.IsNullOrWhiteSpace(assembly.Location))
            .Select(assembly => MetadataReference.CreateFromFile(assembly.Location))
            .Cast<MetadataReference>()
            .ToImmutableArray();

        var syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);
        var compilation = CSharpCompilation.Create(
            assemblyName: "Macaron.InterfaceDelegation.Tests",
            syntaxTrees: [syntaxTree],
            references: references,
            options: new CSharpCompilationOptions(
                outputKind: OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable
            )
        );

        var generator = new InterfaceDelegationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);

        var result = driver.RunGenerators(compilation).GetRunResult().Results.Single();
        var generatedSources = result.GeneratedSources;
        var actual = generatedSources.Length > 2 ? generatedSources[2].SourceText.ToString() : "";

        NUnit.Framework.Assert.That(actual, Is.EqualTo(expected));
    }

    [Test]
    public void ImplementationOfAttributeOnField()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeter
            {
                string Greet(string name);
            }

            public class RealGreeter : IGreeter
            {
                public string Greet(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeter
            {
                [ImplementationOf(typeof(IGreeter))]
                private readonly IGreeter _impl = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IGreeter
                    public string Greet(string name) => _impl.Greet(name);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void ImplementationOfAttributeOnProperty()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeter
            {
                string Greet(string name);
            }

            public class RealGreeter : IGreeter
            {
                public string Greet(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeter
            {
                [ImplementationOf(typeof(IGreeter))]
                private IGreeter Impl { get; } = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IGreeter
                    public string Greet(string name) => Impl.Greet(name);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void MultipleImplementationOfAttributesOnSingleMember()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeterA
            {
                string GreetA(string name);
            }

            public interface IGreeterB
            {
                string GreetB(string name);
            }

            public class RealGreeter : IGreeterA, IGreeterB
            {
                public string GreetA(string name) => $"Hello, {name}!";

                public string GreetB(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeterA, IGreeterB
            {
                [ImplementationOf(typeof(IGreeterA))]
                [ImplementationOf(typeof(IGreeterB))]
                private IGreeter Impl { get; } = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IGreeterA
                    public string GreetA(string name) => Impl.GreetA(name);
                    #endregion

                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IGreeterB
                    public string GreetB(string name) => Impl.GreetB(name);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void MultipleImplementationOfAttributesOnInterfaceImplementedSingleMember()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeterA
            {
                string Greet(string name);

                float this[int index] { get; set; }

                int Value { get; }
            }

            public interface IGreeterB
            {
                void Greet();

                float this[int index] { get; }

                string Value { get; set; }
            }

            public class RealGreeter : IGreeterA, IGreeterB
            {
                string IGreeterA.Greet(string name) => $"Hello, {name}!";

                int IGreeterA.Value => 42;

                float IGreeterA.this[int index]
                {
                    get => 0.0f;
                    set => throw new NotImplementedException();
                }

                void IGreeterB.Greet() { }

                string IGreeterB.Value
                {
                    get => "Hello, world!";
                    set => throw new NotImplementedException();
                }

                float IGreeterB.this[int index]
                {
                    get => 3.14f;
                }
            }

            public partial class TestClass : IGreeterA, IGreeterB
            {
                [ImplementationOf(typeof(IGreeterA), ImplementationMode.Explicit)]
                [ImplementationOf(typeof(IGreeterB), ImplementationMode.Explicit)]
                private RealGreeter Impl { get; } = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IGreeterA
                    string global::Macaron.InterfaceDelegation.Tests.IGreeterA.Greet(string name)
                    {
                        return __Greet(ref Impl, name);

                        #region Local Functions
                        static string __Greet<T>(ref T value, string name) where T : global::Macaron.InterfaceDelegation.Tests.IGreeterA => value.Greet(name);
                        #endregion
                    }

                    float global::Macaron.InterfaceDelegation.Tests.IGreeterA.this[int index]
                    {
                        get
                        {
                            return __Get(ref Impl, index);

                            #region Local Functions
                            static float __Get<T>(ref T impl, int index) where T : global::Macaron.InterfaceDelegation.Tests.IGreeterA => impl[index];
                            #endregion
                        }
                        set
                        {
                            __Set(ref Impl, index, value);

                            #region Local Functions
                            static void __Set<T>(ref T impl, int index, float value) where T : global::Macaron.InterfaceDelegation.Tests.IGreeterA => impl[index] = value;
                            #endregion
                        }
                    }

                    int global::Macaron.InterfaceDelegation.Tests.IGreeterA.Value
                    {
                        get
                        {
                            return __Get(ref Impl);

                            #region Local Functions
                            static int __Get<T>(ref T impl) where T : global::Macaron.InterfaceDelegation.Tests.IGreeterA => impl.Value;
                            #endregion
                        }
                    }
                    #endregion

                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IGreeterB
                    void global::Macaron.InterfaceDelegation.Tests.IGreeterB.Greet()
                    {
                        __Greet(ref Impl);

                        #region Local Functions
                        static void __Greet<T>(ref T value) where T : global::Macaron.InterfaceDelegation.Tests.IGreeterB => value.Greet();
                        #endregion
                    }

                    float global::Macaron.InterfaceDelegation.Tests.IGreeterB.this[int index]
                    {
                        get
                        {
                            return __Get(ref Impl, index);

                            #region Local Functions
                            static float __Get<T>(ref T impl, int index) where T : global::Macaron.InterfaceDelegation.Tests.IGreeterB => impl[index];
                            #endregion
                        }
                    }

                    string global::Macaron.InterfaceDelegation.Tests.IGreeterB.Value
                    {
                        get
                        {
                            return __Get(ref Impl);

                            #region Local Functions
                            static string __Get<T>(ref T impl) where T : global::Macaron.InterfaceDelegation.Tests.IGreeterB => impl.Value;
                            #endregion
                        }
                        set
                        {
                            __Set(ref Impl, value);

                            #region Local Functions
                            static void __Set<T>(ref T impl, string value) where T : global::Macaron.InterfaceDelegation.Tests.IGreeterB => impl.Value = value;
                            #endregion
                        }
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void MultipleImplementationOfAttributesOnMultipleMembers()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IGreeterA
            {
                string GreetA(string name);
            }

            public interface IGreeterB
            {
                string GreetB(string name);
            }

            public class RealGreeter : IGreeterA, IGreeterB
            {
                public string GreetA(string name) => $"Hello, {name}!";

                public string GreetB(string name) => $"Hello, {name}!";
            }

            public partial class TestClass : IGreeterA, IGreeterB
            {
                [ImplementationOf(typeof(IGreeterA))]
                private IGreeterA ImplA { get; } = new RealGreeter();

                [ImplementationOf(typeof(IGreeterB))]
                private IGreeterB ImplB { get; } = new RealGreeter();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestClass
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IGreeterA
                    public string GreetA(string name) => ImplA.GreetA(name);
                    #endregion

                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IGreeterB
                    public string GreetB(string name) => ImplB.GreetB(name);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void InterfaceHasPropertiesAndIndexer()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IPropertyExample
            {
                int Id { get; set; }

                string Name { get; }

                string this[int index] { get; set; }
            }

            public class PropertyExampleImpl : IPropertyExample
            {
                private readonly Dictionary<int, string> _data = new();

                public int Id { get; set; }

                public string Name => "Example";

                public string this[int index]
                {
                    get => _data[index];
                    set => _data[index] = value;
                }
            }

            public partial class TestPropertyDelegation : IPropertyExample
            {
                [ImplementationOf(typeof(IPropertyExample))]
                private readonly IPropertyExample _impl = new PropertyExampleImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPropertyDelegation
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IPropertyExample
                    public int Id
                    {
                        get => _impl.Id;
                        set => _impl.Id = value;
                    }

                    public string Name
                    {
                        get => _impl.Name;
                    }

                    public string this[int index]
                    {
                        get => _impl[index];
                        set => _impl[index] = value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void InterfaceHasMethodOverloads()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface ICalculator
            {
                int Add(int a, int b);

                double Add(double a, double b);
            }

            public class CalculatorImpl : ICalculator
            {
                public int Add(int a, int b) => a + b;

                public double Add(double a, double b) => a + b;
            }

            public partial class TestMethodOverloads : ICalculator
            {
                [ImplementationOf(typeof(ICalculator))]
                private readonly ICalculator _impl = new CalculatorImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestMethodOverloads
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.ICalculator
                    public int Add(int a, int b) => _impl.Add(a, b);

                    public double Add(double a, double b) => _impl.Add(a, b);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void DelegationInStruct()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IStructInterface
            {
                void DoSomething();
            }

            public class StructImpl : IStructInterface
            {
                public void DoSomething() { }
            }

            public partial struct TestStructDelegation : IStructInterface
            {
                [ImplementationOf(typeof(IStructInterface))]
                private readonly IStructInterface _impl;

                public TestStructDelegation()
                {
                    _impl = new StructImpl();
                }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial struct TestStructDelegation
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IStructInterface
                    public void DoSomething() => _impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void DelegationInRecord()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IRecordInterface
            {
                void DoSomething();
            }

            public class RecordImpl : IRecordInterface
            {
                public void DoSomething() { }
            }

            public partial record TestRecordDelegation([ImplementationOf(typeof(IRecordInterface))] IRecordInterface Impl) : IRecordInterface
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial record TestRecordDelegation
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IRecordInterface
                    public void DoSomething() => Impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void DelegationInStructRecord()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IRecordInterface
            {
                void DoSomething();
            }

            public class RecordImpl : IRecordInterface
            {
                public void DoSomething() { }
            }

            public partial record struct TestRecordDelegation([ImplementationOf(typeof(IRecordInterface))] IRecordInterface Impl) : IRecordInterface
            {
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial record struct TestRecordDelegation
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IRecordInterface
                    public void DoSomething() => Impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void PartialImplicitImplementationExistsWithAutoMode()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialAutoImplicit : IFoo
            {
                [ImplementationOf(typeof(IFoo))]
                private readonly IFoo _impl = new FooImpl();

                public void MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialAutoImplicit
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodB() => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void PartialExplicitImplementationExistsWithAutoMode()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialAutoExplicit : IFoo
            {
                [ImplementationOf(typeof(IFoo))]
                private readonly IFoo _impl = new FooImpl();

                void IFoo.MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialAutoExplicit
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodB() => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void ImplicitImplementationMode()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialImplicit : IFoo
            {
                [ImplementationOf(typeof(IFoo), ImplementationMode.Implicit)]
                private readonly IFoo _impl = new FooImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialImplicit
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodA() => _impl.MethodA();

                    public void MethodB() => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void PartialImplicitImplementationExistsWithImplicitMode()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialImplicit : IFoo
            {
                [ImplementationOf(typeof(IFoo), ImplementationMode.Implicit)]
                private readonly IFoo _impl = new FooImpl();

                public void MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialImplicit
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodB() => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void PartialExplicitImplementationExistsWithImplicitMode()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialImplicit : IFoo
            {
                [ImplementationOf(typeof(IFoo), ImplementationMode.Implicit)]
                private readonly IFoo _impl = new FooImpl();

                void IFoo.MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialImplicit
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IFoo
                    public void MethodB() => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void ExplicitImplementationMode()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IService
            {
                void Execute();
            }

            public class ServiceImpl : IService
            {
                public void Execute() { }
            }

            public partial class TestExplicitMode : IService
            {
                [ImplementationOf(typeof(IService), ImplementationMode.Explicit)]
                private readonly IService _impl = new ServiceImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestExplicitMode
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IService
                    void global::Macaron.InterfaceDelegation.Tests.IService.Execute() => _impl.Execute();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void PartialExplicitImplementationExistsWithExplicitMode()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialExplicit : IFoo
            {
                [ImplementationOf(typeof(IFoo), ImplementationMode.Explicit)]
                private readonly IFoo _impl = new FooImpl();

                void IFoo.MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialExplicit
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IFoo
                    void global::Macaron.InterfaceDelegation.Tests.IFoo.MethodB() => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void PartialImplicitImplementationExistsWithExplicitMode()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void MethodA();

                void MethodB();
            }

            public class FooImpl : IFoo
            {
                public void MethodA() { }

                public void MethodB() { }
            }

            public partial class TestPartialExplicit : IFoo
            {
                [ImplementationOf(typeof(IFoo), ImplementationMode.Explicit)]
                private readonly IFoo _impl = new FooImpl();

                public MethodA() { }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestPartialExplicit
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IFoo
                    void global::Macaron.InterfaceDelegation.Tests.IFoo.MethodA() => _impl.MethodA();

                    void global::Macaron.InterfaceDelegation.Tests.IFoo.MethodB() => _impl.MethodB();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void HasAbstractMember()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IAbstractExample
            {
                int GetAnswer();

                void DoSomething();
            }

            public class AbstractExampleImpl : IAbstractExample
            {
                public int GetAnswer() => 42;

                public void DoSomething() { }
            }

            public partial class TestAbstractDelegation : IAbstractExample
            {
                [ImplementationOf(typeof(IAbstractExample))]
                private readonly IAbstractExample _impl = new AbstractExampleImpl();

                public abstract int GetAnswer();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestAbstractDelegation
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IAbstractExample
                    public void DoSomething() => _impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void HasAbstractMemberInParent()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IAbstractExample
            {
                int GetAnswer();

                int Value { get; }
            }

            public class AbstractExampleImpl : IAbstractExample
            {
                public int GetAnswer() => 42;

                public int Value { get => 42; }
            }

            public abstract class TestAbstractDelegationBase
            {
                public abstract int GetAnswer();

                public abstract int Value { get; }
            }

            public partial class TestAbstractDelegation : TestAbstractDelegationBase, IAbstractExample
            {
                [ImplementationOf(typeof(IAbstractExample))]
                private readonly IAbstractExample _impl = new AbstractExampleImpl();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestAbstractDelegation
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IAbstractExample
                    public override int GetAnswer() => _impl.GetAnswer();

                    public override int Value
                    {
                        get => _impl.Value;
                    }
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void HasOverrideMember()
    {
        Assert(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IAbstractExample
            {
                int GetAnswer();

                void DoSomething();

                int Value { get; }
            }

            public class AbstractExampleImpl : IAbstractExample
            {
                public int GetAnswer() => 42;

                public void DoSomething() { }

                int Value { get => 42; }
            }

            public abstract class TestAbstractDelegationBase
            {
                public abstract int GetAnswer();

                public abstract int Value { get; }
            }

            public partial class TestAbstractDelegation : TestAbstractDelegationBase
            {
                [ImplementationOf(typeof(IAbstractExample))]
                private readonly IAbstractExample _impl = new AbstractExampleImpl();

                public override int GetAnswer() => 42;

                public override int Value { get => 42; }
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class TestAbstractDelegation
                {
                    #region Implementation of global::Macaron.InterfaceDelegation.Tests.IAbstractExample
                    public void DoSomething() => _impl.DoSomething();
                    #endregion
                }
            }

            """
        );
    }
}
