using Microsoft.CodeAnalysis;
using static Macaron.InterfaceDelegation.Tests.Helper;

namespace Macaron.InterfaceDelegation.Tests;

[TestFixture]
public sealed class LiftGenerationTests
{
    [Test]
    public void IgnoresNonLiftableMembers_When_UsingLiftAttribute()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System.Collections.Generic;

            namespace Macaron.InterfaceDelegation.Tests;

            // 베이스 클래스 멤버도 포함
            public class Base
            {
                public int BaseValue { get; }

                public void BaseMethod() { }

                // 오버라이드 된 멤버는 무시됨
                public virtual void BaseVirtualMethod() { }
            }

            public abstract class Foo : Base
            {
                // 정적 멤버는 무시됨
                public static Foo Of() => null!;

                public static int StaticValue => 42;

                // 인덱서는 무시됨
                public int this[int index]
                {
                    get => 0;
                    set { }
                }

                public List<object?> Value => null!;

                public int GetAnswer<T>() where T : class => 42;

                public int GetAnswerNullable<T>() where T : class? => 42;

                public List<T?> GetAnswerNullable2<T>() => null!;

                // internal은 internal로 리프팅
                internal int GetAnswer() => 42;

                public override void BaseVirtualMethod() { }

                // public인 아닌 멤버는 무시됨
                protected int HiddenAnswer() => 42;

                // abstract 멤버도 리프팅 대상
                public abstract void AbstractMethod();
            }

            public partial class Bar
            {
                [Lift(includeBaseTypes: true)]
                private readonly Foo _impl = null!;
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class Bar
                {
                    #region global::Macaron.InterfaceDelegation.Tests.Foo
                    public global::System.Collections.Generic.List<object?> Value
                    {
                        get => _impl.Value;
                    }

                    public int GetAnswer<T>()
                        where T : class
                        => _impl.GetAnswer<T>();

                    public int GetAnswerNullable<T>()
                        where T : class?
                        => _impl.GetAnswerNullable<T>();

                    public global::System.Collections.Generic.List<T?> GetAnswerNullable2<T>()
                        => _impl.GetAnswerNullable2<T>();

                    internal int GetAnswer()
                        => _impl.GetAnswer();

                    public void BaseVirtualMethod()
                        => _impl.BaseVirtualMethod();

                    public void AbstractMethod()
                        => _impl.AbstractMethod();

                    public int BaseValue
                    {
                        get => _impl.BaseValue;
                    }

                    public void BaseMethod()
                        => _impl.BaseMethod();
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void LiftedMethodPreservesDefaultParametersFromTargetMethod_When_TargetMethodHasDefaultParameters()
    {
        AssertGeneratedCode(
            sourceCode:
            """
            using System;

            namespace Macaron.InterfaceDelegation.Tests;

            public struct Foo
            {
                // 정적 멤버는 무시됨
                public static Foo Of() => new Foo();

                public static int StaticValue => 42;

                public void Bar(int x, int y = 42, DateTime z = new DateTime()) { }
            }

            public partial class Lifted
            {
                [Lift]
                private Foo _impl { get; } = new();
            }
            """,
            expected:
            """
            // <auto-generated />
            #nullable enable

            namespace Macaron.InterfaceDelegation.Tests
            {
                partial class Lifted
                {
                    #region global::Macaron.InterfaceDelegation.Tests.Foo
                    public void Bar(int x, int y = 42, global::System.DateTime z = default)
                        => _impl.Bar(x, y, z);
                    #endregion
                }
            }

            """
        );
    }

    [Test]
    public void LiftAttributeOptions_WorksAsExpected()
    {
        AssertGeneratedCodes(
            sourceCode:
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public class LiftTargetBase
            {
                public int BaseValue { get; }
            }

            public class LiftTarget : LiftTargetBase
            {
                public int Value => 42;

                public void GetA() { }

                public void GetA(int x) { }

                public void GetB() { }

                public void GetC() { }
            }

            public partial class Lifted
            {
                // 멤버 중복 여부는 변경된 이름을 기준으로 검사
                public void Renamed() { }

                [Lift(
                    includeBaseTypes: true,
                    filter: new[] { "BaseValue", "Value", "GetA", "GetB" },
                    remove: new[] { "GetB" },
                    rename: new[] { "BaseValue:ParentValue", "Value:Answer", "GetA:Renamed" }
                )]
                private readonly LiftTarget _impl = new();

                [Lift(
                    includeBaseTypes: false,
                    filter: new[] { "GetB" }
                )]
                private readonly LiftTarget _impl2 = new();
            }
            """,
            expected:
            [
                """
                // <auto-generated />
                #nullable enable

                namespace Macaron.InterfaceDelegation.Tests
                {
                    partial class Lifted
                    {
                        #region global::Macaron.InterfaceDelegation.Tests.LiftTarget
                        public int Answer
                        {
                            get => _impl.Value;
                        }

                        public void Renamed(int x)
                            => _impl.GetA(x);

                        public int ParentValue
                        {
                            get => _impl.BaseValue;
                        }
                        #endregion
                    }
                }

                """,
                """
                // <auto-generated />
                #nullable enable

                namespace Macaron.InterfaceDelegation.Tests
                {
                    partial class Lifted
                    {
                        #region global::Macaron.InterfaceDelegation.Tests.LiftTarget
                        public void GetB()
                            => _impl2.GetB();
                        #endregion
                    }
                }

                """,
            ]
        );
    }

    [Test]
    public void EmptyLiftOptions_PreserveDefaultGenerationWithoutDiagnostics()
    {
        const string sourceCode =
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public sealed class LiftTarget
            {
                public void Run() { }
            }

            public partial class DefaultLift
            {
                [Lift]
                private readonly LiftTarget _impl = new();
            }

            public partial class ExplicitNullLift
            {
                [Lift(false, null, null, null)]
                private readonly LiftTarget _impl = new();
            }

            public partial class EmptyFilterLift
            {
                [Lift(filter: new string[] { })]
                private readonly LiftTarget _impl = new();
            }

            public partial class EmptyRemoveLift
            {
                [Lift(remove: new string[] { })]
                private readonly LiftTarget _impl = new();
            }

            public partial class EmptyRenameLift
            {
                [Lift(rename: new string[] { })]
                private readonly LiftTarget _impl = new();
            }
            """;

        var result = RunGenerator(sourceCode);

        AssertSuccessfulGeneration(result);
        Assert.Multiple(() =>
        {
            Assert.That(result.Diagnostics, Has.None.Matches<Diagnostic>(static diagnostic => diagnostic.Id == "MAID0004"));
            Assert.That(result.GeneratedSources, Has.Length.EqualTo(5));
            Assert.That(
                result.GeneratedSources.Select(static source => source.SourceText.ToString()),
                Has.All.Contains("public void Run()")
            );
        });
    }

    [Test]
    public void WhitespaceLiftFilter_RemainsAnActiveFilter()
    {
        const string sourceCode =
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public sealed class LiftTarget
            {
                public void Run() { }
            }

            public partial class Wrapper
            {
                [Lift(filter: new[] { " " })]
                private readonly LiftTarget _impl = new();
            }
            """;

        var result = RunGenerator(sourceCode);

        AssertSuccessfulGeneration(result);
        Assert.Multiple(() =>
        {
            Assert.That(result.Diagnostics, Has.None.Matches<Diagnostic>(static diagnostic => diagnostic.Id == "MAID0004"));
            Assert.That(result.GeneratedSources, Is.Empty);
        });
    }

    [Test]
    public void ExposeAndLiftOnSameTarget_ProduceDistinctSources()
    {
        const string sourceCode =
            """
            namespace Macaron.InterfaceDelegation.Tests;

            public interface IFoo
            {
                void Run();
            }

            public sealed class Foo : IFoo
            {
                public int Value => 42;

                public void Run() { }
            }

            public partial class Wrapper : IFoo
            {
                [Expose(typeof(IFoo))]
                [Lift(filter: new[] { "Value" })]
                private readonly Foo _impl = new();
            }
            """;

        var result = RunGenerator(sourceCode);

        AssertSuccessfulGeneration(result);
        Assert.Multiple(() =>
        {
            Assert.That(result.GeneratedSources, Has.Length.EqualTo(2));
            Assert.That(
                result.GeneratedSources.Select(static source => source.HintName),
                Is.Unique
            );
            Assert.That(
                result.GeneratedSources.Count(static source => source.SourceText.ToString().Contains("public void Run()", StringComparison.Ordinal)),
                Is.EqualTo(1)
            );
            Assert.That(
                result.GeneratedSources.Count(static source => source.SourceText.ToString().Contains("public int Value", StringComparison.Ordinal)),
                Is.EqualTo(1)
            );
        });
    }
}
