using System.Text;
using Microsoft.CodeAnalysis;
using System.Security.Cryptography;

namespace Macaron.InterfaceDelegation;

public static class SourceGenerationHelper
{
    public static StringBuilder CreateStringBuilderWithFileHeader()
    {
        var stringBuilder = new StringBuilder();

        stringBuilder.AppendLine("// <auto-generated />");
        stringBuilder.AppendLine("#nullable enable");
        stringBuilder.AppendLine();

        return stringBuilder;
    }

    public static string GetPartialTypeDeclarationString(INamedTypeSymbol typeSymbol)
    {
        var typeKind = GetTypeKindString(typeSymbol);
        var typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        return $"partial {typeKind} {typeName}";
    }

    public static string GetHintName(INamedTypeSymbol typeSymbol, ISymbol targetSymbol, string outputKind)
    {
        var qualifiedName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var targetName = targetSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var identity = $"{qualifiedName}|{targetSymbol.Kind}|{targetName}|{outputKind}";
        byte[] hash;

        using (var algorithm = SHA256.Create())
        {
            hash = algorithm.ComputeHash(Encoding.UTF8.GetBytes(identity));
        }

        var hashString = string.Concat(hash.Take(16).Select(static value => value.ToString("x2")));

        return $"{typeSymbol.Name}_{typeSymbol.Arity}.{outputKind}.{hashString}.g.cs";
    }

    private static string GetTypeKindString(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.IsRecord)
        {
            return typeSymbol.TypeKind is TypeKind.Struct ? "record struct" : "record";
        }

        return typeSymbol.TypeKind switch
        {
            TypeKind.Class => "class",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => throw new InvalidOperationException($"Invalid type kind: {typeSymbol.TypeKind}")
        };
    }
}
